name: CI Check - Build Docker image

on:
  push:

env:
  AWS_REGION: "ap-south-1"
  ECR_REPOSITORY: "pb-recruitment-dev-backend-core-repo"
  ECS_SERVICE: "pb-recruitment-dev-backend-core-svc"
  ECS_CLUSTER: "pb-recruitment-dev-ecs-cluster"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Building Docker image
          docker build -t pb-recruitment-dev-backend-core:$IMAGE_TAG .